version: "3.4"

services:
  web2-api:
    container_name: web.web2-api
    environment:
      - VIRTUAL_HOST=web2-api.albertokato.com
      - VIRTUAL_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://web.postgres-db:5432/web2
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SERVER_PORT=8080
    expose:
      - "8080"
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    tty: true

networks:
  main:
    external:
      name: main
